name: flutter_synth
description: Flutter plugin implementing a native synth on Android, iOS, and MacOS.
version: 1.0.0
homepage: https://github.com/santoxyz/flutter_synth

environment:
  sdk: ">=2.15.1 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.artinoise.flutter_synth
        pluginClass: FlutterSynthPlugin
      ios:
        pluginClass: FlutterSynthPlugin
      macos:
        pluginClass: FlutterSynthPlugin
